### ISSUE TITLE
Error in ts(x) : 'ts' object must have one or more observations

### ISSUE THREAD

**Issue by rterbush** [tourko/tastyworks#1]
Apologies if this is a user error.

Attempts to process a recent confirmation doc produces the above error. Please let me know how I could collect more info for you or let me know what I may be doing wrong.

Calling `read_confirmations()` as follows:
```
read_confirmations("/complete/path/to/file/2018-05-09-XXXXXX-confirmation.pdf")
```

**Comment by tourko** [comment]
Randy,
I am not sure where this error comes from. ts() is a function from "forecast" module, which I don't use. First, could you please try reading one of my confirmations: https://github.com/tourko/tastyworks/tree/master/tests/testthat/confirmations. They are known to work. I would like to rule out that this issue is related to the content of the confirmation. It could be that your confirmation contains a line that I haven't implemented a parser for yet.

**Comment by tourko** [comment]
Randy,
Also the function name is "read_confirmations" and not "read_confirmation".

**Comment by rterbush** [comment]
Running `read_confirmations()` on your example confirmation yields the following:
```
> transactions <- read_confirmations("~/Downloads/2018-01-05-1NE23456-confirmation.pdf")
Proccessing confirmation ~/Downloads/2018-01-05-1NE23456-testconfirmation.pdf
Error in filter(., position == "OPEN") : object 'position' not found
In addition: Warning messages:
1: In data.matrix(data) : NAs introduced by coercion
2: In data.matrix(data) : NAs introduced by coercion
3: In data.matrix(data) : NAs introduced by coercion
```

**Comment by tourko** [comment]
Randy,
I fixed the issue with the example confirmation. It was a corner case related to an option after a stock split. Please try the latest version and let me know if it works for with your confirmation file.

**Comment by rterbush** [comment]
Works perfectly. Thanks for the quick response.
